import type { Model, Field } from '../types/model'

const TYPE_MAP: Record<string, string> = {
  string: 'string',
  text: 'string',
  number: 'number',
  boolean: 'boolean',
  date: 'string',
  richtext: 'string',
}

function toPascalCase(str: string): string {
  return str
    .split(/[-_\s]+/)
    .map(word => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase())
    .join('')
}

function buildModelLookup(models: Model[]): Map<string, string> {
  const lookup = new Map<string, string>()
  for (const model of models) {
    lookup.set(model.id, toPascalCase(model.name))
  }
  return lookup
}

function fieldToTypeString(
  field: Field,
  parentName: string,
  modelLookup: Map<string, string>,
  groupInterfaces: string[]
): string {
  if (field.type === 'group' && field.fields) {
    const groupName = `${parentName}${toPascalCase(field.name)}`
    const groupFields = field.fields
      .map(f => {
        const tsType = TYPE_MAP[f.type] || 'unknown'
        const optional = f.required ? '' : '?'
        return `  ${f.name}${optional}: ${tsType}`
      })
      .join('\n')

    groupInterfaces.push(`export interface ${groupName} {\n${groupFields}\n}`)
    return groupName
  }

  if (field.type === 'relation') {
    const targetName = field.targetModelId
      ? modelLookup.get(field.targetModelId)
      : undefined

    const typeName = targetName || 'string'
    return field.multiple ? `${typeName}[]` : typeName
  }

  return TYPE_MAP[field.type] || 'unknown'
}

export function generateTypes(models: Model[]): string {
  const modelLookup = buildModelLookup(models)
  const sections: string[] = []

  sections.push('// This file is auto-generated by @architect-cms/delivery')
  sections.push('// Do not edit manually. Regenerate with: npx architect-delivery generate-types')
  sections.push('')

  for (const model of models) {
    const interfaceName = toPascalCase(model.name)
    const groupInterfaces: string[] = []

    const fields = model.fields
      .map(field => {
        const tsType = fieldToTypeString(field, interfaceName, modelLookup, groupInterfaces)
        const optional = field.required ? '' : '?'
        return `  ${field.name}${optional}: ${tsType}`
      })
      .join('\n')

    // Add group interfaces before the main interface
    for (const gi of groupInterfaces) {
      sections.push(gi)
      sections.push('')
    }

    sections.push(`export interface ${interfaceName} {`)
    if (fields) {
      sections.push(fields)
    }
    sections.push('}')
    sections.push('')
  }

  return sections.join('\n')
}
